### ISSUE TITLE
Add Redirect on Shortcode Login

### ISSUE THREAD

**Issue by zogot** [pronamic/wp-pronamic-secure-content#1]
https://github.com/pronamic/wp-pronamic-secure-content/blob/master/src/Pronamic/Secure/Plugin.php#L60 could use the add_query_arg function to also append the ID on the redirect. This could make for use in the shortcode method, to redirect back to that page when successful.

**Comment by remcotolsma** [comment]
For now, we have decided to no longer maintain and develop the "WP Pronamic Secure Content" plugin. Therefore, we will close this issue and archive this repository.
